#!/bin/sh
# Copyright(c) 2011-2014 Shenzhen TP-LINK Technologies Co.Ltd.
# file     portspeed
# brief    
# author   Zhu Xianfeng<zhuxianfeng@tp-link.net>
# version  1.0.0
# date     25Jun14
# history  arg 1.0.0, 25Jun14, Zhu Xianfeng, Create the file. 

if [ $# -ne 4 ]; then
    exit 0
fi

local port=$1
local speed=$2
local duplex=$3
local autoneg=$4
local ctrl_speed=0x40
local ctrl_duplex=0x100
local ctrl_sw_rst=0x8000
local ctrl_reg=0x0
local ctrl_val=0x0

case $speed in
    1000)
		ctrl_speed=0x40
        ;;
    100)
		ctrl_speed=0x2000
        ;;
    10)
		ctrl_speed=0x0
        ;;
    *)
        exit 1
        ;;
esac

case $duplex in
    "full")
		ctrl_duplex=0x100
        ;;
    "half")
		ctrl_duplex=0x0
        ;;
    *)
        exit 1
        ;;
esac

if [ "$duplex" != "full" -a "$duplex" != "half" ]; then
    exit 1
fi
if [ "$autoneg" != "on" -a "$autoneg" != "off" ]; then
    exit 1
fi

if [ "$speed" = "1000" -o "$autoneg" = "on" ]; then
    ssdk_sh port autoNeg restart $1
    exit 0
else
    #ssdk_sh port speed set $1 $speed
    #ssdk_sh port duplex set $1 $duplex
	let "port-=1"
	let "ctrl_val=$ctrl_speed|$ctrl_duplex|$ctrl_sw_rst"
	ssdk_sh debug phy set $port $ctrl_reg $ctrl_val
    exit 0
fi
